package configgen

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/cloudboot/cloudboot-ng/internal/models"
)

// Generator 配置生成器
type Generator struct {
	templates map[string]*template.Template
}

// NewGenerator 创建配置生成器
func NewGenerator() *Generator {
	g := &Generator{
		templates: make(map[string]*template.Template),
	}

	// 注册内置模板
	g.registerBuiltinTemplates()

	return g
}

// Generate 生成配置文件
func (g *Generator) Generate(profile *models.OSProfile) (string, error) {
	// 验证配置
	if err := g.Validate(profile); err != nil {
		return "", fmt.Errorf("validation failed: %w", err)
	}

	// 根据OS类型选择模板
	templateName := g.selectTemplate(profile.Distro)
	tmpl, ok := g.templates[templateName]
	if !ok {
		return "", fmt.Errorf("template not found for OS type: %s", profile.Distro)
	}

	// 准备模板数据
	data := g.prepareTemplateData(profile)

	// 渲染模板
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template execution failed: %w", err)
	}

	return buf.String(), nil
}

// selectTemplate 根据OS类型选择模板
func (g *Generator) selectTemplate(osType string) string {
	switch osType {
	case "centos7", "centos8":
		return "kickstart"
	case "ubuntu20", "ubuntu22":
		return "preseed"
	case "sles12", "sles15":
		return "autoyast"
	default:
		return "kickstart" // 默认
	}
}

// prepareTemplateData 准备模板数据
func (g *Generator) prepareTemplateData(profile *models.OSProfile) map[string]interface{} {
	return map[string]interface{}{
		"Profile":    profile,
		"Partitions": profile.Config.Partitions,
		"Network":    profile.Config.NetworkConfig,
		"Packages":   profile.Config.Packages,
		"PostScript": profile.Config.PostScript,
		"RepoURL":    profile.Config.RepoURL,
		"Helpers":    g.getHelperFuncs(),
	}
}

// getHelperFuncs 获取模板辅助函数
func (g *Generator) getHelperFuncs() template.FuncMap {
	return template.FuncMap{
		"parseSize": func(sizeStr string) string {
			// Size format: "100GB", "20%", etc.
			// For now, simple conversion: strip suffix and multiply by 1024 for MB
			// TODO: Handle percentage-based sizes
			return sizeStr // Return as-is for now, template will handle
		},
		"isSwap": func(mount string) bool {
			return mount == "swap"
		},
		"joinDNS": func(dnsServers []string) string {
			if len(dnsServers) == 0 {
				return "8.8.8.8"
			}
			return dnsServers[0] // Use first DNS server
		},
	}
}

// RegisterTemplate 注册自定义模板
func (g *Generator) RegisterTemplate(name, content string) error {
	tmpl, err := template.New(name).Funcs(g.getHelperFuncs()).Parse(content)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	g.templates[name] = tmpl
	return nil
}

// registerBuiltinTemplates 注册内置模板
func (g *Generator) registerBuiltinTemplates() {
	// Kickstart 模板 (CentOS/RHEL)
	g.RegisterTemplate("kickstart", kickstartTemplate)

	// Preseed 模板 (Ubuntu/Debian)
	g.RegisterTemplate("preseed", preseedTemplate)

	// AutoYaST 模板 (SUSE)
	g.RegisterTemplate("autoyast", autoyastTemplate)
}

const kickstartTemplate = `# Kickstart for {{ .Profile.Distro }}
# Generated by CloudBoot NG

# System authorization
auth --enableshadow --passalgo=sha512

# Use network installation
url --url={{ .RepoURL }}

# Keyboard layouts
keyboard us

# System language
lang en_US.UTF-8

# Network information
{{ with .Network -}}
network --bootproto=static --ip={{ .IP }} --netmask={{ .Netmask }} --gateway={{ .Gateway }} --nameserver={{ call $.Helpers.joinDNS .DNS }} --hostname={{ .Hostname }}
{{- end }}

# Root password
{{ if .Profile.Config.RootPasswordHash -}}
rootpw --iscrypted {{ .Profile.Config.RootPasswordHash }}
{{ else -}}
rootpw --iscrypted $6$rounds=4096$salt$hash
{{- end }}

# System timezone
{{ if .Profile.Config.Timezone -}}
timezone {{ .Profile.Config.Timezone }} --isUtc
{{ else -}}
timezone Asia/Shanghai --isUtc
{{- end }}

# Bootloader configuration
bootloader --location=mbr --boot-drive=sda

# Clear the Master Boot Record
zerombr

# Partition clearing information
clearpart --all --initlabel --drives=sda

# Disk partitioning information
{{ range .Partitions -}}
{{ if call $.Helpers.isSwap .MountPoint -}}
part swap --fstype=swap --size={{ .Size }}
{{ else -}}
part {{ .MountPoint }} --fstype={{ .FSType }} --size={{ .Size }}
{{ end -}}
{{ end }}

# Packages
%packages
@core
{{ range .Packages -}}
{{ . }}
{{ end }}
%end

# Post-installation script
{{ if .PostScript -}}
%post --log=/root/ks-post.log
{{ .PostScript }}
%end
{{- end }}

# Reboot after installation
reboot
`

const preseedTemplate = `# Preseed for {{ .Profile.Distro }}
# Generated by CloudBoot NG

# Localization
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

# Network configuration
{{ with .Network -}}
d-i netcfg/choose_interface select auto
d-i netcfg/get_ipaddress string {{ .IP }}
d-i netcfg/get_netmask string {{ .Netmask }}
d-i netcfg/get_gateway string {{ .Gateway }}
d-i netcfg/get_nameservers string {{ .DNS }}
d-i netcfg/get_hostname string {{ .Hostname }}
{{- end }}

# Mirror settings
d-i mirror/country string manual
d-i mirror/http/hostname string {{ .RepoURL }}

# Partitioning
d-i partman-auto/method string regular
d-i partman-auto/expert_recipe string \\
{{ range .Partitions -}}
{{ .MountPoint }} :: {{ .Size }} {{ .FSType }} . \\
{{ end }}

# Package selection
tasksel tasksel/first multiselect standard
{{ range .Packages -}}
d-i pkgsel/include string {{ . }}
{{ end }}

# Post-installation
d-i preseed/late_command string \\
{{ .PostScript }}
`

const autoyastTemplate = `<?xml version="1.0"?>
<!DOCTYPE profile>
<!-- AutoYaST for {{ .Profile.Distro }} -->
<!-- Generated by CloudBoot NG -->
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <networking>
    <interfaces config:type="list">
      <interface>
        <bootproto>static</bootproto>
        {{ with .Network -}}
        <ipaddr>{{ .IP }}</ipaddr>
        <netmask>{{ .Netmask }}</netmask>
        <hostname>{{ .Hostname }}</hostname>
        {{- end }}
      </interface>
    </interfaces>
  </networking>

  <partitioning config:type="list">
    <drive>
      <device>/dev/sda</device>
      <use>all</use>
      <partitions config:type="list">
        {{ range .Partitions -}}
        <partition>
          <mount>{{ .MountPoint }}</mount>
          <filesystem config:type="symbol">{{ .FSType }}</filesystem>
          <size>{{ .Size }}</size>
        </partition>
        {{ end }}
      </partitions>
    </drive>
  </partitioning>

  <software>
    <packages config:type="list">
      {{ range .Packages -}}
      <package>{{ . }}</package>
      {{ end }}
    </packages>
  </software>

  <scripts>
    <post-scripts config:type="list">
      <script>
        <filename>post.sh</filename>
        <source><![CDATA[
{{ .PostScript }}
        ]]></source>
      </script>
    </post-scripts>
  </scripts>
</profile>
`
